Repository wecode-bootcamp-korea/24-1st-MANNAMCHU-frontend, pull requests merged in 2021-09, with the labels that each got.

#1 [24기 정행운] ADD: Footer 레이아웃 추가
  package-lock.json
  src/Routes.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.scss
  src/components/Nav/Navbar.js
Labels: Status: Accepted

#6 [24기 조성환][feature/btncomponent] Add : Tags 공용 컴포넌트 추가 (new, sale, best)
  src/components/Tags/Tags.js
  src/components/Tags/Tags.scss
  src/styles/common.scss
Labels: Status: Accepted

#10 [24기 김현재] [Feature/favicon] 💄Add : favicon 구현 완료
  public/favicon/android-chrome-192x192.png
  public/favicon/android-chrome-512x512.png
  public/favicon/apple-touch-icon.png
  public/favicon/browserconfig.xml
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon.ico
  public/favicon/mstile-150x150.png
  public/favicon/safari-pinned-tab.svg
  public/favicon/site.webmanifest
  public/index.html
  src/Main/Main.js
  src/Main/Main.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#11 [24기 정행운] [Feature/footer] 피드백 반영
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: Status: Accepted

#12 [24기 김현재] [feature/common.css]💄 Add : main theme font 추가
  src/styles/common.scss
Labels: Status: 리뷰 요청

#13 [24기 김현재] [feature/tag-styling]💄 Add: Tag component style 수정
  src/components/Tags/Tags.scss
Labels: Status: Accepted

#4 [24기 정행운] [Feature/login] 로그인화면 레이아웃 완료, 기능 구현 예정
  src/Routes.js
  src/components/Nav/Navbar.js
  src/pages/Main/Main.scss
  src/pages/Sign/Login/Login.js
  src/pages/Sign/Login/Login.scss
  src/pages/Sign/Signup/Signup.scss
  src/pages/Sign/logo.png
Labels: Status: Accepted

#14 [24기 김현재] [feature/main-layout] 🐛 Fix : link button 해상도에 따라 글자 무너지는 것 보완
  src/pages/Main/Main.scss
  src/pages/Main/MainLinks/MainLink/MainLink.scss
  src/pages/Main/MainLinks/MainLinks.scss
Labels: Status: 리뷰 요청

#5 [24기 김현재] [Feature/listpage] ✨ Add : product list page 필수 구현사항 구현 완료
  public/data/filterData.json
  public/data/listData.json
  src/components/Tags/Tags.js
  src/pages/Product/ListHeader/ListHeader.js
  src/pages/Product/ListHeader/ListHeader.scss
  src/pages/Product/Product.js
  src/pages/Product/Product.scss
  src/pages/Product/ProductLists/ProductList/ProductList.js
  src/pages/Product/ProductLists/ProductList/ProductList.scss
  src/pages/Product/ProductLists/ProductLists.js
  src/pages/Product/ProductLists/ProductLists.scss
  src/styles/reset.scss
Labels: Status: 리뷰 요청

#15 [24기 조성환][feature/detailPage] Add : 옵션 수량 변경 및 선택한 옵션 취소 기능 추가
  public/data/detailPage.json
  src/pages/Product/ProductDetail/ProductDetail.js
  src/pages/Product/ProductDetail/ProductDetail.scss
  src/pages/Product/ProductDetail/ProductDetailComponent/ImgList/ImgList.js
  src/pages/Product/ProductDetail/ProductDetailComponent/ImgList/ImgList.scss
  src/pages/Product/ProductDetail/ProductDetailComponent/InfoConfig/InfoConfig.js
  src/pages/Product/ProductDetail/ProductDetailComponent/InfoConfig/InfoConfigOptPrice/InfoConfigOptPrice.js
  src/pages/Product/ProductDetail/ProductDetailComponent/InfoConfig/InfoConfigOptPrice/InfoConfigOptPrice.scss
  src/pages/Product/ProductDetail/ProductDetailComponent/InfoConfig/InfoConfigSelOpt/InfoConfigSelOpt.js
  src/pages/Product/ProductDetail/ProductDetailComponent/InfoOrder/InfoOrder.js
  src/pages/Product/ProductDetail/ProductDetailComponent/InfoOrder/InfoOrder.scss
  src/pages/Product/ProductDetail/ProductDetailComponent/InfoPrice/InfoPrice.js
Labels: Status: Accepted

#16 [24기 정행운] [Feature/login] 로그인 스타일링 수정
  src/pages/Sign/Login/Login.js
  src/pages/Sign/Login/Login.scss
Labels: Status: Accepted

#9 [24기 정행운] [Feature/signup] 회원 가입 레이아웃 완료, 추가 기능 구현 예정
  src/Routes.js
  src/pages/Main/MainLinks/MainLink/MainLink.js
  src/pages/Sign/Signup/Signup.js
  src/pages/Sign/Signup/Signup.scss
  src/pages/Sign/맛남츄로고.png
Labels: Status: Accepted

#7 [24기 조성환][feature/cartPage] Add : 장바구니 수량 수정 기능 추가, delete 기능 추가
  public/data/cartListData.json
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartComponent/CartProduct/CartProduct.js
  src/pages/Cart/CartComponent/WishList/WishList.js
  src/pages/Cart/CartComponent/WishList/WishList.scss
  src/pages/Product/ProductDetail/ProductDetail.js
Labels: Status: Accepted

#17 [24기 김현재] [feature/listpage-scroll] ✨ Add: 무한 스크롤 기능 추가
  src/pages/Product/ProductLists/ProductLists.js
Labels: Status: 리뷰 요청

#18 [24기 조성환] [feature/detailPage] Fix : 상세 페이지 버튼 border 수정
  src/pages/Product/ProductDetail/ProductDetailComponent/InfoOrder/InfoOrder.scss
Labels: Status: Accepted

#8 [24기 정행운] [Feature/navbar] Navbar 레이아웃 완료
  src/Routes.js
  src/components/Nav/Navbar.js
  src/components/Nav/Navbar.scss
  src/pages/Sign/Login/Login.js
  src/pages/Sign/Login/Login.scss
Labels: Status: 리뷰 요청

#19 [24기 정행운] [Feature/signup] 통신 문제 해결
  src/Routes.js
  src/pages/Sign/Signup/Signup.js
  src/pages/Sign/Signup/Signup.scss
Labels: Status: Accepted

#20 [24기 김현재] [feature/navbar-style] 🐛 Fix : navbar 위치 고정 및 z-index 수정
  src/components/Nav/Navbar.scss
  src/pages/Main/MainSlides/MainSlide/MainSlide.scss
  src/pages/Main/MainSlides/MainSlides.scss
  src/pages/Sign/Login/Login.scss
Labels: Status: Accepted

#23 [24기 김현재] 📝 Add : readme 추가
  README.md
Labels: Status: Accepted

#25 [24기 정행운] 모달 스크롤, 회원 가입 이메일 유효성 수정
  src/components/Nav/Navbar.js
  src/pages/Sign/Signup/Signup.js
  src/pages/Sign/Signup/Signup.scss
Labels: Status: Accepted

#26 [24기 정행운] Navbar, Signup, Login 브랜치 완료
  src/components/Nav/Navbar.js
  src/pages/Sign/Login/Login.js
  src/pages/Sign/Login/Login.scss
  src/pages/Sign/Signup/Signup.js
  src/pages/Sign/Signup/Signup.scss
Labels: Status: 리뷰 요청

#24 [24기 조성환] [feature/fixFetch] Fix : 통신 관련 데이터 구조 수정
  src/config.js
  src/pages/Cart/Cart.js
  src/pages/Cart/CartComponent/CartProduct/CartProduct.js
  src/pages/Product/ProductDetail/ProductDetail.js
  src/pages/Product/ProductDetail/ProductDetail.scss
  src/pages/Sign/Login/Login.js
  src/pages/Sign/Signup/Signup.js
Labels: Status: Conflict 해결 요청

#27 [24기 조성환] [feature/deploy] Fix : 배포 서버 ip 수정
  src/config.js
Labels: Status: 리뷰 요청

#28 [24기 조성환] [Feature/fixError] 로그인 회원가입 글자 수정
  src/pages/Sign/Login/Login.js
  src/pages/Sign/Signup/Signup.js
Labels: Status: 리뷰 요청
